# -*- coding: utf-8 -*-
"""make_url_cache_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uA2Ov2nltlBKqyax1D6C_6OfxGH-u7wc
"""

import pandas as pd
import datetime as dt
from datetime import datetime
from urllib.parse import quote
import requests
now = str(datetime.now())
time = pd.date_range(end = now, periods = 2, freq = "30D")
start_time = str(time[0])[0:10]
end_time = str(time[1])[0:10]
now

start_time_1H = pd.date_range(end = start_time, periods = 2, freq = "1H")
start_time_1H = quote(str(start_time_1H[0])[0:16])
start_time_1H

end_time_1H = pd.date_range(start = end_time, periods = 2, freq = "1D59min")
end_time_1H = quote(str(end_time_1H[1])[0:16])
end_time_1H

lst_min_max_lat_lon_事件圈圈 = [
    "min_lat=22.4342&max_lat=22.89&min_lon=120.1393&max_lon=120.4398",
    "min_lat=23.4386&max_lat=23.5347&min_lon=120.397&max_lon=120.5106",
    "min_lat=22.9036&max_lat=23.2027&min_lon=120.0584&max_lon=120.2666",
    "min_lat=21.8727&max_lat=22.8734&min_lon=120.4398&max_lon=120.9212",
    "min_lat=24.075452&max_lat=24.42158&min_lon=120.49468&max_lon=120.742974",
    "min_lat=24.576&max_lat=24.7401&min_lon=120.7107&max_lon=120.9529",
    "min_lat=23.519469&max_lat=23.793247&min_lon=120.1385103&max_lon=120.7179493",
    "min_lat=23.7868&max_lat=24.2007&min_lon=120.2524&max_lon=120.6884",
    "min_lat=24.8276&max_lat=25.0968&min_lon=121.0815&max_lon=121.3961",
    "min_lat=24.9344&max_lat=25.155&min_lon=121.3699&max_lon=121.5263",
    "min_lat=24.6188&max_lat=24.6422&min_lon=121.807&max_lon=121.8355",
    "min_lat=24.7465&max_lat=24.9093&min_lon=120.8888&max_lon=121.1645",
    "min_lat=25.0494&max_lat=25.1775&min_lon=121.6186&max_lon=121.8143",
    "min_lat=24.94624&max_lat=25.175258&min_lon=121.362369&max_lon=121.62475"]

lst_min_max_lat_lon_國家測站 = [
    "min_lat=22.2097&max_lat=23.1145&min_lon=119.89160000000001&max_lon=120.6875",
    "min_lat=23.214100000000002&max_lat=23.7592&min_lon=120.14930000000001&max_lon=120.75829999999999",
    "min_lat=22.679100000000002&max_lat=23.4272&min_lon=119.81070000000001&max_lon=120.51429999999999",
    "min_lat=21.6482&max_lat=23.0979&min_lon=120.19210000000001&max_lon=121.1689",
    "min_lat=23.850952&max_lat=24.646079999999998&min_lon=120.24698000000001&max_lon=120.990674",
    "min_lat=24.3515&max_lat=24.9646&min_lon=120.46300000000001&max_lon=121.2006",
    "min_lat=23.294969000000002&max_lat=24.017747&min_lon=119.8908103&max_lon=120.9656493",
    "min_lat=23.5623&max_lat=24.4252&min_lon=120.0047&max_lon=120.9361",
    "min_lat=24.6031&max_lat=25.3213&min_lon=120.83380000000001&max_lon=121.6438",
    "min_lat=24.7099&max_lat=25.3795&min_lon=121.1222&max_lon=121.774",
    "min_lat=24.3943&max_lat=24.866699999999998&min_lon=121.55930000000001&max_lon=122.08319999999999",
    "min_lat=24.522000000000002&max_lat=25.1338&min_lon=120.64110000000001&max_lon=121.4122",
    "min_lat=24.8249&max_lat=25.401999999999997&min_lon=121.3709&max_lon=122.062",
    "min_lat=24.72174&max_lat=25.399758&min_lon=121.114669&max_lon=121.872452"]

lst_area = [
    "高雄",
    "嘉義",
    "台南",
    "屏東",
    "台中",
    "苗栗",
    "雲林",
    "彰化",
    "桃園",
    "新北",
    "宜蘭",
    "新竹",
    "基隆",
    "台北"]

def print_file(str_line,io):
    print(str_line)
    io.write(str_line+"\n")

def loop_url_事件(lst_min_max_lat_lon_事件圈圈,io):
    for str_min_max_lat_lon_事件圈圈 in lst_min_max_lat_lon_事件圈圈:
        str_url_事件 = f'https://iotai-dev.cameo.tw/api/v2/iot/events?start_time={start_time}%2000%3A00%3A00&end_time={end_time}%2023%3A59%3A59&{str_min_max_lat_lon_事件圈圈}'
        print_file(str_url_事件,io)

def loop_url_圈圈(lst_min_max_lat_lon_事件圈圈,lst_area,io):
    int_cnt=0
    while int_cnt < len(lst_min_max_lat_lon_事件圈圈):
        print(int_cnt,lst_min_max_lat_lon_事件圈圈[int_cnt],lst_area[int_cnt])
        str_url_圈圈 = f'https://iotai-dev.cameo.tw/api/v2/iot/circles/avg?start_time={start_time}%2000%3A00%3A00&end_time={end_time}%2023%3A59%3A59&area={quote(lst_area[int_cnt])}&score_threshold=40&{lst_min_max_lat_lon_事件圈圈[int_cnt]}'
        int_cnt+=1
        print_file(str_url_圈圈,io)

def loop_url_國家測站(lst_min_max_lat_lon_國家測站,io):
    for str_min_max_lat_lon_國家測站 in lst_min_max_lat_lon_國家測站:
        str_url_國家測站 = f'https://iotai-dev.cameo.tw/_/api/v2/epa_station/rawdata?fields=wind_direct%2Cwind_speed&start_time={start_time_1H}&end_time={end_time_1H}&{str_min_max_lat_lon_國家測站}' 
        print_file(str_url_國家測站,io)

def gen_all_url():
    io = open(f"make_url_cache_{end_time}.csv", "w")
    loop_url_事件(lst_min_max_lat_lon_事件圈圈,io)
    loop_url_圈圈(lst_min_max_lat_lon_事件圈圈,lst_area,io)
    loop_url_國家測站(lst_min_max_lat_lon_國家測站,io)
    io.close()

gen_all_url() 
lst = open(f"make_url_cache_{end_time}.csv", "r").read().split("\n")
for str_url in lst:
    print(str_url)
    r = requests.get(str_url)
    #print(r.text[0:300])